# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Grant permission
        run: chmod +x app/gradlew

      - name: Building android
        uses: sparkfabrik/android-build-action@v1.0.0
        with:
          project-path: app
          output-path: my-app.apk

